spring:
  # DataSource Config
  datasource:
    druid:
      # 数据库 1
      db1:
        url: jdbc:mysql://127.0.0.1:3306/base?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Hongkong
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        initialSize: 5
        minIdle: 5
        maxActive: 20
      # 数据库 2
#      db2:
#        url: jdbc:mysql://127.0.0.1:3306/base?useSSL=false&useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Hongkong
#        username: root
#        password: root
#        driver-class-name: com.mysql.jdbc.Driver
#        initialSize: 5
#        minIdle: 5
#        maxActive: 20

  messages:
    encoding: UTF-8
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

  druid:
    init:
      prefix: /druid/*
      allow:
      deny: 192.168.1.100
      loginUsername: root
      loginPassword: 123123
      resetEnable: false

#mybatis配置
mybatis-plus:
  global-config:
    #是否开启xml自动刷新，生产环境请关闭
    refresh: true
#自定义属性配置
system:
  yml:
    #权限配置
    security:
      jwt:
        secret: k09BQnaF
        expiration: 604800 #7Days
    #上传配置
    upload:
      #文件上传存储路径
      file-root-path: /Users/xiongmengui/uploads/
    #初始密码
    initialPassword: 123456

